---
- hosts: all



  tasks:
    - name: "Reconfigure {{ guest_name }} "
      vsphere_guest:
        validate_certs: False      
        vcenter_hostname: "{{ vcenter_server }}"
        guest: "{{ guest_name }}"
        state: reconfigured
        vm_hardware:
            num_cpus: 1
            memory_mb: 1024
      delegate_to: localhost